version: "3.8"

services:
  react:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - node
    networks:
      - app-network
  node:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: appuser
      DB_PASSWORD: apppassword
      DB_NAME: appdb
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    expose:
      - "3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
    
