version: "3.8"

services:
  nuxt:
    build: ./frontend
    ports:
      - "3000"
    depends_on:
      - node
  node:
    build: ./backend
    ports:
      - "8000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: appuser
      DB_PASSWORD: apppassword
      DB_NAME: appdb
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./loadbalance/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nuxt
      - node
    networks:
      - app-network
      - default
    command: /bin/sh -c "sleep 10 && nginx -g 'daemon off;'"
networks:
  app-network:
    name: app-network